version: '3.1'

services:
#  api_service:
#    container_name: test_app
#    depends_on:
#      - postgres
#    build:
#      context: .
#    ports:
#      - '8080:8080'

  postgres:
    image: 'postgres:latest'
    container_name: test_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - './config/:/etc/prometheus/'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'