global:
  scrape_interval: 5s
  evaluation_interval: 55s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'spring-actuator'
    metrics_path: '/api/v1/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ '10.0.10.28:8080' ]